version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  test_cli:
    executor: node/default
    steps:
      - checkout
      - run:
          command: sudo npm i -g tj-cli-cmd
          name: Install cli tool
      - run:
          command: tj-cli-cmd start-cloud-run --pass-percentage=50 --token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTJkNzE3NDJjNGI0MmNjMWM0NWMxNjAiLCJlbWFpbCI6ImtoYWxpZEB5b3BtYWlsLmNvbSIsInN0YXR1cyI6MSwicm9sZXMiOnsicm9sZSI6ImFkbWluIiwibmFtZSI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiIiLCJhY2Nlc3NfaWQiOnsidHlwZSI6WyJDcmVhdGUiLCJVcGRhdGUiLCJSZWFkIiwiRGVsZXRlIl0sImRlc2NyaXB0aW9uIjoiIiwidGl0bGUiOiJDUlVEIn19LCJwcm9maWxlIjpudWxsLCJzdWJzY3JpcHRpb24iOnsiY29uc3VtZWRfcGxhbiI6eyJwcm9qZWN0X2xpbWl0IjowLCJ0ZXN0X2Nhc2VfbGltaXQiOjAsInRlc3RfcnVuX2xpbWl0IjowfSwic3RhdHVzX2NvZGUiOjJ9LCJpbnZpdGVkX2J5IjpudWxsLCJ2ZXJpZmljYXRpb24iOnsiZW1haWxfdmVyaWZpZWQiOnRydWUsImVtYWlsX3ZyZl90b2tlbiI6bnVsbH0sImlhdCI6MTY5OTg2NjkwNCwiZXhwIjoxNjk5ODk1NzA0fQ.LgaRqE2XTjqDRVEJAS6arA_M3Jl2HB_vyLNeIyz3Y_Q 42
          name: Write my name


workflows:
  testjet_test:
    jobs:
      - test
