version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm i -g tj-cli-cmd
          name: Install cli tool
      - run:
          command: tj-cli-cmd write khalid
          name: Write my name


workflows:
  test_my_app:
    jobs:
      - test
