name: Test with Testjet

on:
  - push
  - workflow_dispatch

jobs:
  test:
    env:
      HOST: http://localhost:3000
      TOKEN: ${{ secrets.BEARER_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Print host
        run: echo "${{ env.HOST }}"

      - name: Print secret
        run: echo "${{ env.TOKEN }}"

      - name: Install Testjet cli tool
        run: npm install -g tj-cli-cmd

      - name: Write my name
        run: tj-cli-cmd write khalid

      # - name: Get Test run details
      #   id: testjet_test
      #   run: |
      #     echo "isTestPassed=$(tj-cli-cmd get-test-run 861)\n" >> $GITHUB_OUTPUT

      # - name: Print result
      #   run: echo "${{ steps.testjet_test.outputs.isTestPassed }}"

      # - name: Exit if the test failed
      #   if: steps.testjet_test.outputs.isTestPassed != 'true'
      #   run: exit 1

      # - name: Check if test has been passed
      #   run: echo "This will be printed only if the test has been passed"

      - name: Run test on the cloud
        id: testjet_test
        run: |
          echo "returnOutput=$(tj-cli-cmd clr --token=${{env.TOKEN}} 26)\n" >> $GITHUB_OUTPUT
        
      - name: Print result
        run: echo "${{ steps.testjet_test.outputs.returnOutput }}"

  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Print deployment logs
        run: echo "This will be printed only if the build job is successful"
