name: Test with Testjet
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Testjet cli tool
        run: npm install -g tj-cli-cmd@1.0.0
      - name: Write my name
        run: testjet-cli-cmd write khalid