name: Test with Testjet

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Print Build logs
        run: echo "Build successful"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g tj-cli-cmd
      - run: tj-cli-cmd clr --token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM5ZmM1M2QxNWY0OTI3YWE0OGUyYzAiLCJlbWFpbCI6ImtoYWxpZDEwMUB5b3BtYWlsLmNvbSIsInN0YXR1cyI6MSwicm9sZXMiOnsicm9sZSI6ImFkbWluIiwibmFtZSI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiIiLCJhY2Nlc3NfaWQiOnsidHlwZSI6WyJDcmVhdGUiLCJVcGRhdGUiLCJSZWFkIiwiRGVsZXRlIl0sInRpdGxlIjoiQ1JVRCIsImRlc2NyaXB0aW9uIjoiIn19LCJwcm9maWxlIjp7Im5hbWUiOiJBbGFza2EiLCJjb3VudHJ5X2lkIjp7InNob3J0TmFtZSI6IlVTIiwibmFtZSI6IlVuaXRlZCBTdGF0ZXMiLCJwaG9uZUNvZGUiOjF9fSwic3Vic2NyaXB0aW9uIjp7ImNvbnN1bWVkX3BsYW4iOnsicHJvamVjdF9saW1pdCI6MCwidGVzdF9jYXNlX2xpbWl0IjowLCJ0ZXN0X3J1bl9saW1pdCI6MCwibW9iaWxlX3Byb2plY3RfbGltaXQiOjN9LCJzdGF0dXNfY29kZSI6Mn0sImludml0ZWRfYnkiOm51bGwsInZlcmlmaWNhdGlvbiI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZW1haWxfdnJmX3Rva2VuIjpudWxsfSwiaWF0IjoxNzAxODQwNjE2LCJleHAiOjE3MDE4Njk0MTZ9.pyt2APfTPkqRZ-uTGEW2fW7U0623dgqdF1lMYieCWBA --pass-percentage=100 862


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Print deployment logs
        run: echo "This will be printed only if the build job is successful"
